namespace UptoboxDl.UptoboxClient;

public enum StatusCode
{
    Success = 0,
    An_error_occured = 1,
    Invalid_Credentials = 2,
    Expect_at_least_one_value = 3,
    Wrong_format = 4,
    Need_premium_account = 5,
    Missing_Parameter = 6,
    Invalid_Parameter = 7,
    Insufficient_credit = 8,
    Unsupported_field = 9,
    Unprocessable_request = 10,
    Too_much_fail_attempt = 11,
    Missing_token = 12,
    Invalid_token = 13,
    Voucher_is_already_used = 14,
    Unsupported_conversion = 15,
    Waiting_needed = 16,
    Password_required = 17,
    Data_unchanged = 18,
    Invalid_voucher = 19,
    Not_available = 20,
    Permission_denied = 21,
    Permission_granted = 22,
    Request_has_failed = 23,
    Request_has_succeeded_partially = 24,
    Server_temprorarily_unavailable = 25,
    Invalid_password = 26,
    Require_an_authenticated_user = 27,
    File_not_found = 28,
    You_have_reached_the_streaming_limit_for_today = 29,
    Folder_not_found = 30,
    Expect_a_numeric_value = 31,
    Limit_reached = 32,
    Invalid_data = 34,
    File_will_be_available_soon = 35,
    No_subscription_found = 36,
    Stream_is_not_available = 37,
    Filesize_need_premium = 38,
    You_need_to_wait_before_requesting_a_new_download_link = 39,
}